---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    chart: clientApp
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: {{ .Values.name }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    chart: clientApp
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: us.gcr.io/studious-lore-148916/{{ .Values.name }}:{{ .Values.tag }}
        ports:
          - containerPort: 5000
